### ISSUE TITLE
Release 0.2.2

### ISSUE THREAD

**Issue by dontub** [andreas-glaser/doctrine-rql#10]
Could you release version 0.2.2? Even though there are no code changes since 0.2.1, it would be nice to use a released version without installing doctrine/data-fixtures.

**Comment by andreas-glaser** [comment]
Absolutely, I will look into it!

**Comment by andreas-glaser** [comment]
branch 0.3 is there now. have a look and see what you feel should be added/removed before i create a release tag in the next days

**Comment by dontub** [comment]
Thanks. Made two PRs. When looking at `ORMVisitor` I was wondering for what the `reset()` method is good for. When `$this->aliasMap = [];` is moved to `append()` there's no need for `reset()`. Could the `QueryBuilder` and `$autoRootAlias` be given as constructor args, `append()` be removed, and `visitQuery()` be made public?
I think the name of class `ORMVisitorFactory` is not really fitting as no `ORMVisitor` is returned at all.

Side note: This might be of interest as you as well: https://github.com/libgraviton/rql-parser/issues/17. Though you probably have already seen it in the release notes of rql-parser.
